stages:
  - lint
  - security

semgrep:
  image: semgrep/semgrep
  stage: lint
  script:
    - semgrep --config "r2c" --json --metrics=off --debug > semgrep-results.json
  only:
    - branches
  variables:
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
  artifacts:
    paths:
      - semgrep-results.json
    expire_in: 1 week

owasp-dependency-check:
  stage: security
  image: owasp/dependency-check:latest
  script:
    - dependency-check --scan ./ --out ./reports --format JSON
  artifacts:
    paths:
      - reports/dependency-check-report.json
    expire_in: 1 week

